In [2]:
#loading importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy as sp
import os
import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv(r"D:\Netflix_movies_project\Dataset\netflix_titles.csv")

In [4]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,23-Dec-16,2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,20-Dec-18,2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,16-Nov-17,2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,1-Jan-20,2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB

In [6]:
df.describe()

       release_year
count   7787.000000
mean    2013.932580
std        8.757395
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2018.000000
max     2021.000000

<!-- فيه missing values في:
director (كتير)
cast
country
date_added
rating
الأعمدة النصية محتاجة cleaning:
trim
splitting
date_added محتاجة تحوي -->

#Initial data exploration revealed missing values in key columns such as #director (~30%), cast, and country. The dataset also required type conversion for date fields and text preprocessing for categorical variables.

In [9]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

<h1> Cleaning </h1>

In [11]:
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna(df['country'].mode()[0])
df['rating'] = df['rating'].fillna('Not Rated')

In [12]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df = df.dropna(subset=['date_added'])

In [13]:
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6207,s6208,TV Show,The Challenge,Unknown,"Jamie Chung, Landon Lueck, Diem Brown, Mike 'T...",United States,2020-12-15,2006,TV-14,2 Seasons,Reality TV,Reality show alumni must compete in grueling p...
5004,s5005,TV Show,Pup Academy,Unknown,"Christian Convery, Don Lake, Chance Hurstfield...",United States,2020-12-15,2020,TV-Y,2 Seasons,"Kids' TV, TV Comedies",Furry friends take a re-bark-able journey in t...
877,s878,Movie,Beyond the Boundary: ICC Women's T20 World Cup...,Anna Stone,Unknown,United States,2020-08-14,2020,TV-G,59 min,"Documentaries, International Movies, Sports Mo...","With highlights from the 2020 tourney, this pr..."
6423,s6424,Movie,The Great Raid,John Dahl,"Benjamin Bratt, James Franco, Connie Nielsen, ...","United States, Australia",2019-11-01,2005,R,133 min,"Action & Adventure, Dramas","In World War II, a battalion goes on a daring ..."
4319,s4320,Movie,My Fuhrer,Dani Levy,"Helge Schneider, Ulrich Mühe, Sylvester Groth,...",Germany,2018-05-07,2007,TV-14,91 min,"Comedies, International Movies",Germany's most celebrated actor is commissione...

In [14]:
df['title'] = df['title'].str.strip()
df['country'] = df['country'].str.strip()
df['director'] = df['director'].str.strip()

In [15]:
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month

In [16]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [17]:
df['type'].value_counts()
df['country'].value_counts().head(10)
df['rating'].value_counts()

rating
TV-MA        2861
TV-14        1928
TV-PG         804
R             665
PG-13         386
TV-Y          279
TV-Y7         270
PG            247
TV-G          194
NR             83
G              39
Not Rated       7
TV-Y7-FV        6
UR              5
NC-17           3
Name: count, dtype: int64

The majority of Netflix content is targeted toward mature audiences, with TV-MA and TV-14 dominating the platform.

In [19]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added
0,s1,TV Show,3%,Unknown,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,2020-08-14,2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020,8
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,2016-12-23,2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016,12
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,2018-12-20,2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018,12
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,2017-11-16,2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017,11
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,2020-01-01,2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...",2020-10-19,2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020,10
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019,3
7784,s7785,Movie,Zulu Man in Japan,Unknown,Nasty C,United States,2020-09-25,2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020,9
7785,s7786,TV Show,Zumbo's Just Desserts,Unknown,"Adriano Zumbo, Rachel Khoo",Australia,2020-10-31,2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020,10
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,Unknown,"United Kingdom, Canada, United States",2020-03-01,2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020,3

In [20]:
df['country'] = df['country'].str.split(',')
df = df.explode('country')
df['country'] = df['country'].str.strip()

<h1> Analysis </h1>

In [22]:
df['year_added'].value_counts().sort_index()

year_added
2008       2
2009       2
2010       1
2011      15
2012       4
2013      13
2014      37
2015     113
2016     572
2017    1517
2018    2081
2019    2584
2020    2474
2021     149
Name: count, dtype: int64

In [23]:
df.groupby(['year_added', 'type']).size()

year_added  type
2008        Movie         1
            TV Show       1
2009        Movie         2
2010        Movie         1
2011        Movie        15
2012        Movie         4
2013        Movie         6
            TV Show       7
2014        Movie        26
            TV Show      11
2015        Movie        75
            TV Show      38
2016        Movie       338
            TV Show     234
2017        Movie      1122
            TV Show     395
2018        Movie      1587
            TV Show     494
2019        Movie      1868
            TV Show     716
2020        Movie      1682
            TV Show     792
2021        Movie       116
            TV Show      33
dtype: int64

In [24]:
df.groupby('country')['type'].count().sort_values(ascending=False).head(10)

country
United States     3797
India              990
United Kingdom     722
Canada             412
France             349
Japan              286
Spain              215
South Korea        212
Germany            199
Mexico             154
Name: type, dtype: int64

In [25]:
type(df['duration'])

pandas.core.series.Series

In [46]:
df['duration_int'] = df['duration'].str.extract('(\d+)')

In [48]:
df['duration_int'] = df['duration_int'].astype(float)

In [50]:
df['duration_int'].dtype

dtype('float64')

In [52]:
df.groupby('type')['duration_int'].mean()

type
Movie      99.965951
TV Show     1.801176
Name: duration_int, dtype: float64

Movie >> minutes , Tv_Show >> Seasons

In [56]:
df['duration_int'] = df['duration_int'].astype(float)

movies = df[df['type'] == 'Movie']
tv = df[df['type'] == 'TV Show']

movies['duration_int'].mean()
tv['duration_int'].mean()

1.8011760382212423

In [58]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,duration_int
0,s1,TV Show,3%,Unknown,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,2020-08-14,2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020,8,4.0
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,2016-12-23,2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016,12,93.0
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,2018-12-20,2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018,12,78.0
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,2017-11-16,2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017,11,80.0
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,2020-01-01,2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020,1,123.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7784,s7785,Movie,Zulu Man in Japan,Unknown,Nasty C,United States,2020-09-25,2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020,9,44.0
7785,s7786,TV Show,Zumbo's Just Desserts,Unknown,"Adriano Zumbo, Rachel Khoo",Australia,2020-10-31,2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020,10,1.0
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,Unknown,United Kingdom,2020-03-01,2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020,3,90.0
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,Unknown,Canada,2020-03-01,2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020,3,90.0
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,Unknown,United States,2020-03-01,2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020,3,90.0

In [62]:
df.to_csv('Dataset_After_Cleannig.csv', index=False)